remote_theme: "mmistakes/minimal-mistakes"

# Site Settings
minimal_mistakes_skin    : "dark" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
name                     : "Jim Slemin"
description              : "A small obscure corner of the net."
url                      : "https://jimslemin.github.io"
